services:
  frontend:
    build:
      context: ./frontend
      target: deps
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  gateway:
    environment:
      - CHOKIDAR_USEPOLLING=true

  parser-service:
    environment:
      - CHOKIDAR_USEPOLLING=true

  transaction-service:
    environment:
      - CHOKIDAR_USEPOLLING=true
