server {
    listen 80;
    server_name localhost;

    # Serve Next.js Frontend
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve Gateway REST APIs
    location /api/ {
        # proxy_pass to gateway port 3000
        proxy_pass http://gateway:3000/api/;
        proxy_set_header Host $host;
    }

    # Serve Gateway Parse Endpoint (For Testing)
    location /parse {
        proxy_pass http://gateway:3000/parse;
        proxy_set_header Host $host;
    }
}
